[tool.poetry]
name = "crypto_client"
version = "0.3.0"
description = ""
authors = ["Calvin Krist <calvin.krist@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
wheel = "^0.37.1"
